#!/usr/bin/python3

import RPi.GPIO as GPIO
from time import sleep

#set up numbering for points
GPIO.setmode(GPIO.BCM)

#setup pin numbers
in1 = 24
in2 = 25
enA = 23

#Set up all pins as output pins
GPIO.setup(in1, GPIO.OUT)
GPIO.setup(in2, GPIO.OUT)
GPIO.setup(enA, GPIO.OUT)

#setup PWM Cycle
pCycle = p.(enA, 1000)

#motor Forward
GPIO.output(in1,GPIO.HIGH)
GPIO.output(in2,GPIO.LOW)
GPIO.output(enA, GPIO.HIGH)
